let number = 10;
console.log(number);
number += 5;
console.log(number);
number *= 2;
console.log(number);
number -= 4;
console.log(number);
number /= 3;
console.log(number);
number %= 6;
console.log(number);